spring:
  application:
    name: neoeats
  config:
    import:
      - classpath:properties/application-feign.yaml
      - classpath:properties/application-logging.yaml
qrmenu:
  base-url: https://neotech.az