name: Checkstyle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Set HTTPS URL for submodule with token
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          
      - name: Checkout main repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      - name: Upload Checkstyle Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/
