name: Checkstyle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Update submodule URLs
        run: |
          git config --global --add url."https://${{ secrets.ORG_CI_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global --add url."https://${{ secrets.ORG_CI_TOKEN }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"
          
      - name: Checkout main repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      - name: Upload Checkstyle Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/
