name: Checkstyle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout main repository and submodules with HTTPS override
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
        env:
          ORG_CI_TOKEN: ${{ secrets.ORG_CI_TOKEN }}
        # override Git SSH with HTTPS+token before submodule fetch
        before: |
          git config --global url."https://${ORG_CI_TOKEN}@github.com/".insteadOf "git@github.com:"
          git config --global url."https://${ORG_CI_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain

      - name: Upload Checkstyle Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/
